### PR TITLE
Miscellaneous tests to improve coverage

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by dpsanders** [comment]
Can I merge this?

**Comment by lbenet** [comment]
I just noticed (after merging #215) that there are no new tests on such functionality. Can you add them in this PR?

**Comment by dpsanders** [comment]
I have added a few tests of `parse(Interval, string)`. Is that what you were referring to?

**Comment by lbenet** [comment]
I was thinking to include things like `@interval("[1]")`, etc, as mentioned in #215.

**Comment by lbenet** [comment]
In any case, I'm in favor of merging this.

**Comment by dpsanders** [comment]
Some were already included [here](https://github.com/dpsanders/ValidatedNumerics.jl/blob/11bf694f878194a48a446c7e4f31800404b66d69/test/interval_tests/construction.jl#L262)

**Comment by dpsanders** [comment]
Will merge this once turns green.

**Pull request merged**
