### PR TITLE
Update NEWS for 0.1

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
I guess this should be merged once everything in #23 is included, probably together with tagging the new release.

**Comment by dpsanders** [comment]
Once you've had a look at the example notebooks, everything in #23 is now finished!

**Comment by dpsanders** [comment]
Sorry, I see that you already merged the examples, thanks. From my point of view, we seem to be ready to release 0.1!

**Comment by lbenet** [comment]
I agree. So, just go on and tag this version along with this PR!

Congratulations!

**Comment by lbenet** [comment]
This is merged! The rest is on your side :-)

**Pull request merged**
