### PR TITLE
Separate out root finding into separate submodule

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
Can you include this somewhere in the documentation?

**Comment by dpsanders** [comment]
I have added the doc and rebased against master.

**Comment by lbenet** [comment]
I'll check this right away.

**Comment by lbenet** [comment]
LGTM. Shall I go ahead and merge?

**Comment by lbenet** [comment]
... but the tests are failing.

**Comment by lbenet** [comment]
Tests are passing again. Is this ready to be merged?

**Comment by dpsanders** [comment]
Finally... Yes, I think so.

**Comment by lbenet** [comment]
Done. Great!

**Pull request merged**
