### PR TITLE
0.6 update: type -> mutable struct

### PR DESCRIPTION
**Pull request by miguelraz**
I believe this should get this script up to speed with [version 0.6](https://github.com/JuliaLang/julia/blob/master/NEWS.md)

### CODE REVIEW

**Comment by lbenet** [comment]
As far as I know, the new syntax is not supported in Julia 0.5, including `@compat` tricks.

**Comment by miguelraz** [comment]
Feared so - just looking to get a bit more in touch with how to upstream changes in package development. 
Sorry for any inconvenience, just looking to learn - any comments appreciated.
You may store the pull request until master moves to 0.6 or kill it.

**Comment by lbenet** [comment]
What is the difference between this PR and #258 ?

**Comment by miguelraz** [comment]
None, must have got confused when trying to fish some of these out.
Kill it with :fire:.

**Pull request closed without merging**
