### PR TITLE
Update to Julia 1.0

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot!

I think travis needs to be upgraded, so Julia 0.6 is dropped there as well.

**Comment by lbenet** [comment]
This should be rebased to master, to include the fixes of #285

**Comment by dpsanders** [comment]
Rebased.

**Comment by dpsanders** [comment]
This is ready to merge @lbenet!

**Comment by lbenet** [comment]
Great! Thanks! Merging!

**Comment by lbenet** [comment]
Since we are deploying the documentation, perhaps it is a good idea to implement [this patch](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/236.patch). If you prefer to leave it for another PR, it's ok with me. Simply, go ahead and merge.

Thanks a lot for the effort!

**Pull request merged**
