### PR TITLE
Rewrite tests to use Base.Test

### PR DESCRIPTION
**Pull request by lbenet**
Currently, some tests (involving some functions) do not pass due
to CRlibm

### CODE REVIEW

**Comment by lbenet** [comment]
Addresses #193

ITF1788 files not yet modified, since this is better to using directly the tools provided by ITF1788...

**Comment by lbenet** [comment]
Incidentally, these changes will only be useful once we leave 0.4 without support.

**Comment by dpsanders** [comment]
Great, thanks! On Julia 0.4 you need `using BaseTestNext` to use `@testset`.

**Comment by lbenet** [comment]
What about `@compat`?

**Comment by dpsanders** [comment]
Not sure what you are asking about `@compat`?

**Comment by dpsanders** [comment]
https://github.com/JuliaCI/BaseTestNext.jl

**Comment by lbenet** [comment]
I though that `@compat using Base.Test` could save us replacing that for
```julia
if VERSION >= v"0.5.0-dev+7720"
    using Base.Test
else
    using BaseTestNext
    const Test = BaseTestNext
end
```
in each file. But i couldn't find it.

How do we deal with the `REQUIRES` in this case?

**Comment by dpsanders** [comment]
I think you only need it in runtests.jl, since everything is included from
there?

**Comment by lbenet** [comment]
No, though that could indeed be a solution; each included file has the `using` command.

**Comment by dpsanders** [comment]
If I remember correctly, each file has it so that they can be run
independently if needed. But the tests should work on 0.4 just adding the
basetestnext in runtests.jl

**Comment by dpsanders** [comment]
Looking good! Is this ready to merge?

**Comment by lbenet** [comment]
Not yet; on the one hand, there is something weird with Julia 0.6; I'm also trying to transform the ITF1788 tests. I'll let you know when I think it is ready.

**Comment by dpsanders** [comment]
Don't worry about 0.6. I finally got tests to pass on the fix_radius_0.6 branch that requires us to change from FixedSizeArrays.jl to StaticArrays.jl. 

I suggest we merge this and the itf1788 tests can be in a separate pr.

**Comment by lbenet** [comment]
Ok. Then go ahead.

**Comment by lbenet** [comment]
One of the tests that is not passing in v0.6 yields the following output
```
Operations on boxes: Error During Test
  Test threw an exception of type ErrorException
  Expression: 2A == IntervalBox(2 .. 4, 6 .. 8)
  type TypeName has no field primary
  Stacktrace:
   [1] promote_type_nested(::Type{T} where T<:Tuple) at /Users/benet/.julia/v0.6/FixedSizeArrays/src/core.jl:181
   [2] construct_similar(...) at /Users/benet/.julia/v0.6/FixedSizeArrays/src/core.jl:230
   [3] macro expansion at /Users/benet/.julia/v0.6/FixedSizeArrays/src/mapreduce.jl:81 [inlined]
   [4] map at /Users/benet/.julia/v0.6/FixedSizeArrays/src/mapreduce.jl:119 [inlined]
   [5] *(::Int64, ::ValidatedNumerics.IntervalBox{2,Float64}) at /Users/benet/.julia/v0.6/FixedSizeArrays/src/ops.jl:95
   [6] macro expansion at /Users/benet/.julia/v0.5/ValidatedNumerics/test/multidim_tests/multidim.jl:13 [inlined]
   [7] macro expansion at ./test.jl:853 [inlined]
   [8] anonymous at ./<missing>:?
```

I guess this is related to the new type nomenclature... 

I haven't checked if there are other problems.

**Comment by dpsanders** [comment]
I'm not sure what exactly it's related to, but it's fixed by the latest StaticArrays.jl update.

**Comment by dpsanders** [comment]
Thanks!

**Comment by dpsanders** [comment]
Do you have the ITF1788 tests switched to `@testset` for the files that are already included (not the new ones)?

**Pull request merged**
