### PR TITLE
Replaced 'with 53 bits of precision' with subscript 53

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
After merging #12, conflicts arose here. Can you solve them? I think they appear in REQUIRE and .travis.yml.

**Comment by dpsanders** [comment]
This can now me merged.

**Comment by dpsanders** [comment]
Assuming you agree with the change?

**Comment by lbenet** [comment]
Due to the previous merge, this has to be rebased...

**Comment by dpsanders** [comment]
Rebased, ready to merge.

**Pull request merged**
