### PR TITLE
Hyperbolic functs

### PR DESCRIPTION
**Pull request by lbenet**
Once #56 is merged, this PR implements the hyperbolic functions and the corresponding inverses. Only `sinh` and `cosh` are used from `CRlibm.jl` (the rest are not defined). The others pass correctly the ITF1788 tests.

### CODE REVIEW

**Comment by lbenet** [comment]
Rebased (to current version of "control_rounding" branch) and repushed; this is also to rerun the tests (one of them hang for ever in travis).

**Comment by lbenet** [comment]
Re-rebased...

**Comment by dpsanders** [comment]
Could you please rebase this a final time? Then I think it's ready to merge.

**Comment by dpsanders** [comment]
OK, I did it ;)

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
