### PR TITLE
Include ITF1788 files and rewrite to use function of form `sin(x::BigFloat, RoundUp)`

### PR DESCRIPTION
**Pull request by dpsanders**
Miscellaneous changes.

### CODE REVIEW

**Comment by lbenet** [comment]
I think this is ready to be merged. Shall I go ahead?

**Comment by dpsanders** [comment]
I think so, yes!

**Comment by lbenet** [comment]
Great work! This is really getting somewhere! Merging...

**Comment by PallHaraldsson** [comment]
I'm not sure, is info here outdated? :

https://github.com/oheim/ITF1788/blob/master/README.md

**Comment by dpsanders** [comment]
Not yet outdated, no, there's still quite some work to do before the package is compliant with the standard (unfortunately!).

**Pull request merged**
