### PR TITLE
Increase test coverage of intervals code

### PR DESCRIPTION
**Pull request by dpsanders**
Up from 75% to 88% test coverage with this PR.

EDIT: Found a couple of bugs by adding tests!

### CODE REVIEW

**Comment by lbenet** [comment]
Can you rebase to the last version in master? I just merged #47...

I guess at the moment the best is to review the code as it is, and eventually squash the commits, right?

**Comment by dpsanders** [comment]
Thanks for comments. Rebased and squashed.

**Comment by lbenet** [comment]
Except for the comment on `^` in automatic_differentiation.jl, the rest LGTM.

**Comment by dpsanders** [comment]
Oops, I was getting confused with `^`, thanks!

**Comment by dpsanders** [comment]
This is ready to merge.

**Comment by lbenet** [comment]
Merged! Nice :-)

**Pull request merged**
