### PR TITLE
Rewrite Krawczyk's method, rename findroots to find_roots and add tests

### PR DESCRIPTION
**Pull request by lbenet**
Rewrote Krawczyk's method keeping the implementation of Newton's method
as standard. Now, both methods use the function `clean_roots!` which is
located in newton.jl.

The tests check both methods using find_roots.

### CODE REVIEW

**Comment by lbenet** [comment]
This pull request addresses two points in the list #23, namely, Krawczyk's method and renaming `findroots`

**Comment by lbenet** [comment]
Tests pass; it's ready to be merged.

**Comment by lbenet** [comment]
Just pushed the new commits.

What I dislike of the idea of simply passing the operators is that it seems that it influences strongly the performance. That's the reason I tend to avoid that practice.

**Comment by lbenet** [comment]
Tests pass. Incidentally, have you checked the time that the tests run in julia v0.3.8 vs v0.4-dev? It's ~1min vs 32 sec, respectively...

**Comment by dpsanders** [comment]
Ah yes, you could be right about the performance when passing the operators.

**Comment by dpsanders** [comment]
If you prefer, I'll just merge it and then we can work on it.

**Comment by lbenet** [comment]
Let me correct the error message and see if I can do something more condensed for newton and krawczyk

**Comment by lbenet** [comment]
Tests pass... I think this is ready to be merged

**Comment by dpsanders** [comment]
Rebased into a single commit. (Or would you prefer to do it yourself?)

**Comment by lbenet** [comment]
It's ok with me.

**Comment by dpsanders** [comment]
OK, I'll merge once Travis gives the green light.

**Comment by lbenet** [comment]
Green light there :-)

**Comment by lbenet** [comment]
I have merged it...

**Comment by dpsanders** [comment]
:+1:

**Pull request merged**
