### PR TITLE
Changes in newton with tests, and improvements in interval_trig

### PR DESCRIPTION
**Pull request by lbenet**
This pull-request essentially does the same as #9 but with the updated version in master. In addition, it includes (previously commented) tests for the auto_diff module and new tests for newton. Some tests for newton uncovered an inconsistency in the type of the interval induced in interval_trig; I hope this doesn't create new problems, though tests pass.

### CODE REVIEW

**Comment by lbenet** [comment]
Tests for v0.3 are failing (v0.4 pass), since `parse(BigFloat,x)` with `x` an `AbstractString` is not being recognized. This should be solved once JuliaLang/Compat.jl/pull/76 is merged.

**Comment by dpsanders** [comment]
I suggest just adding that to ValidatedNumerics for the moment.

**Comment by lbenet** [comment]
Done... finally :-)

**Comment by dpsanders** [comment]
Thanks! :)

**Pull request merged**
