### PR TITLE
Fix 1D Newton by checking correctly whether midpoint is exactly a root

### PR DESCRIPTION
**Pull request by dpsanders**
- Fixes Newton by correctly checking if a midpoint is exactly a root, and moving the midpoint a bit if it is.

- Fixes Krawczyk in the case that the midpoint has derivative 0.

### CODE REVIEW

**Comment by lbenet** [comment]
Tests are not passing; more precisely, the root-finding tests.

**Comment by dpsanders** [comment]
Tests are now passing! @lbenet

**Comment by dpsanders** [comment]
This is ready. Is it OK with you to merge @lbenet ?

**Comment by lbenet** [comment]
I'm also in favor of merging. Yet, some tests (0.6) are problematic, which is known. Do we go ahead?

**Comment by dpsanders** [comment]
Yes, 0.6 is simply not ready yet. (it is still alpha after all)

**Comment by lbenet** [comment]
Thanks! This was truly needed!

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
