### PR TITLE
Correct `@interval` macros.

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by lbenet** [comment]
After merging #12, conflicts arose here. Can you solve them? I think they appear in REQUIRE and .travis.yml; maybe also in some of the tests files.

**Comment by dpsanders** [comment]
I have rebased. Please let me add documentation and tests to fix things we have discussed.

**Comment by dpsanders** [comment]
Do you think I should squash some commits?

**Comment by lbenet** [comment]
Yeah; makes life easier :-)

**Comment by lbenet** [comment]
Incidentally, running the test in julia 0.4 send a deprecation warning:
```julia
WARNING: int(x::FloatingPoint) is deprecated, use round(Int,x) instead.
```

I think this is a good time to require Compat.jl to get rid of this warning. What do you think?

Then I could merge and we look for whatever consequences.

**Comment by dpsanders** [comment]
Sure, can you make a PR against my PR with the changes needed to include Compat.jl? I haven't used it very much.

**Comment by dpsanders** [comment]
Or just use the following for the moment?
```
a = 3.1
convert(Int, floor(a))
```

**Comment by lbenet** [comment]
I'll merge and add a parallel pull-request... Much easier :-)

**Comment by dpsanders** [comment]
I would like to do the `rationalize` but leave a `BigFloat` as is. Does that sound like a good compromise?

**Comment by lbenet** [comment]
Do the tests pass? If yes, I think it makes sense.

**Pull request merged**
